# ███████╗████████╗ █████╗ ██████╗ ███████╗██╗  ██╗██╗██████╗
# ██╔════╝╚══██╔══╝██╔══██╗██╔══██╗██╔════╝██║  ██║██║██╔══██╗
# ███████╗   ██║   ███████║██████╔╝███████╗███████║██║██████╔╝
# ╚════██║   ██║   ██╔══██║██╔══██╗╚════██║██╔══██║██║██╔═══╝
# ███████║   ██║   ██║  ██║██║  ██║███████║██║  ██║██║██║
# ╚══════╝   ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝╚═╝
# The minimal, blazing-fast, and infinitely customizable prompt.
#

"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 2000

format = """
$os\
$hostname\
$username\
$sudo\
$directory\
$git_branch\
$git_status\
$git_state\
$nodejs\
$perl\
$python\
$rust\
$zig\
$ruby\
$golang\
$lua\
$php\
$java\
$c\
$kotlin\
$haskell\
$package\
$vagrant\
$conda\
$docker_context\
${custom.vagrant_context}\
$time\
$cmd_duration\
$line_break$character"""

palette = 'spaceduck'

[palettes.gruvbox_dark_material]
color_bg0           = '#1d2021'  # Background
color_bg1           = '#282828'  # Slightly lighter
color_bg2           = '#3c3836'  # Selection
color_bg3           = '#665c54'  # Comments
color_fg0           = '#d4be98'  # Foreground
color_fg1           = '#e2cca9'  # Bright
color_white         = '#e2cca9'  # White
color_red           = '#ea6962'  # Red
color_orange        = '#e78a4e'  # Orange
color_yellow        = '#d8a657'  # Yellow
color_green         = '#a9b665'  # Green
color_cyan          = '#89b482'  # Cyan
color_blue          = '#7daea3'  # Blue
color_purple        = '#d3869b'  # Purple

[palettes.onedark]
color_bg0           = '#282c34'  # Background
color_bg1           = '#2c323d'  # Slightly lighter
color_bg2           = '#3e4451'  # Selection
color_bg3           = '#5c6370'  # Comments
color_fg0           = '#abb2bf'  # Foreground
color_fg1           = '#c8ccd4'  # Bright
color_white         = '#ffffff'  # White
color_red           = '#e06c75'  # Red
color_orange        = '#d19965'  # Orange
color_yellow        = '#e5c07b'  # Yellow
color_green         = '#98c379'  # Green
color_cyan          = '#56b6c2'  # Cyan
color_blue          = '#61afef'  # Blue
color_purple        = '#c678dd'  # Purple

[palettes.spaceduck]
color_bg0           = '#0f111b'  # Background
color_bg1           = '#16192e'  # Slightly lighter
color_bg2           = '#1e2340'  # Selection
color_bg3           = '#5c6370'
color_fg0           = '#ecf0c1'  # Foreground
color_fg1           = '#f0f1ce'  # Bright white
color_white         = '#f0f1ce'  # Bright white
color_red           = '#e33400'  # Red
color_orange        = '#e39400'  # Orange
color_yellow        = '#f2ce00'  # Yellow
color_green         = '#5ccc96'  # Green
color_cyan          = '#00a3cc'  # Cyan
color_blue          = '#7a5ccc'  # Blue
color_purple        = '#b3a1e6'  # Purple

[palettes.tokyonight]
color_bg0           = '#1a1b26'  # Background
color_bg1           = '#24283b'  # Slightly lighter
color_bg2           = '#292e42'  # Selection
color_bg3           = '#414868'  # Comments
color_fg0           = '#c0caf5'  # Foreground
color_fg1           = '#c0caf5'  # Bright
color_white         = '#c0caf5'  # White
color_red           = '#f7768e'  # Red
color_orange        = '#ff9e64'  # Orange
color_yellow        = '#e0af68'  # Yellow
color_green         = '#9ece6a'  # Green
color_cyan          = '#7dcfff'  # Cyan
color_blue          = '#7aa2f7'  # Blue
color_purple        = '#bb9af7'  # Purple

[palettes.tokyonight_storm]
color_bg0           = '#24283b'  # Background
color_bg1           = '#292e42'  # Slightly lighter
color_bg2           = '#343b58'  # Selection
color_bg3           = '#414868'  # Comments
color_fg0           = '#c0caf5'  # Foreground
color_fg1           = '#c0caf5'  # Bright
color_white         = '#c0caf5'  # White
color_red           = '#f7768e'  # Red
color_orange        = '#ff9e64'  # Orange
color_yellow        = '#e0af68'  # Yellow
color_green         = '#9ece6a'  # Green
color_cyan          = '#7dcfff'  # Cyan
color_blue          = '#7aa2f7'  # Blue
color_purple        = '#bb9af7'  # Purple

[palettes.dracula]
color_bg0           = '#282a36'  # Background
color_bg1           = '#343746'  # Slightly lighter
color_bg2           = '#44475a'  # Selection
color_bg3           = '#6272a4'  # Comments
color_fg0           = '#f8f8f2'  # Foreground
color_fg1           = '#f8f8f2'  # Bright
color_white         = '#f8f8f2'  # White
color_red           = '#ff5555'  # Red
color_orange        = '#ffb86c'  # Orange
color_yellow        = '#f1fa8c'  # Yellow
color_green         = '#50fa7b'  # Green
color_cyan          = '#8be9fd'  # Cyan
color_blue          = '#8be9fd'  # Blue
color_purple        = '#bd93f9'  # Purple

[palettes.kanagawa]
color_bg0           = '#1f1f28'  # sumiInk3
color_bg1           = '#2a2a37'  # sumiInk4
color_bg2           = '#363646'  # sumiInk5
color_bg3           = '#54546d'  # sumiInk6
color_fg0           = '#dcd7ba'  # fujiWhite
color_fg1           = '#dcd7ba'  # fujiWhite
color_white         = '#dcd7ba'  # fujiWhite
color_red           = '#c34043'  # autumnRed
color_orange        = '#ffa066'  # surimiOrange
color_yellow        = '#e6c384'  # carpYellow
color_green         = '#98bb6c'  # springGreen
color_cyan          = '#7fb4ca'  # springBlue
color_blue          = '#7e9cd8'  # crystalBlue
color_purple        = '#957fb8'  # oniViolet

[os]
disabled = false
style = "fg:color_cyan bold"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
Macos = "󰀵"
Linux = "󰌽"
Arch = "󰣇"
Debian = "󰣚"
Fedora = "󰣛"
Manjaro = ""
Pop = ""

[hostname]
disabled = false
ssh_only = false
style = "fg:color_blue bold"
format = '[ on ](fg:color_bg3)[$hostname]($style)'

[username]
show_always = true
style_user = "fg:color_blue bold"
style_root = "fg:color_red bold"
format = '[ as ](fg:color_bg3)[$user]($style)'

[sudo]
disabled = false
style = "fg:color_red bold"
symbol = ' '
format = "[$symbol]($style)"

[directory]
style = "fg:color_yellow bold"
format = "[ $path]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "fg:color_green"
format = '[ $symbol $branch]($style)'

[git_status]
style = "fg:color_green"
format = '[($all_status$ahead_behind)]($style)'

[git_state]
style = "fg:color_green dim"
format = '[ $state($progress_current/$progress_total)]($style)'

[nodejs]
symbol = ""
style = "fg:color_green"
format = '[ $symbol $version]($style)'

[c]
symbol = ""
style = "fg:color_blue"
format = '[ $symbol $version]($style)'

[rust]
symbol = "󱘗"
style = "fg:color_orange"
format = '[ $symbol $version]($style)'

[perl]
symbol = ""
style = "fg:color_cyan"
format = '[ $symbol $version]($style)'

[ruby]
symbol = ""
style = "fg:color_red"
format = '[ $symbol $version]($style)'

[lua]
symbol = ""
style = "fg:color_blue"
format = '[ $symbol $version]($style)'

[zig]
symbol = ""
style = "fg:color_orange"
format = '[ $symbol $version]($style)'

[golang]
symbol = ""
style = "fg:color_cyan"
format = '[ $symbol $version]($style)'

[php]
symbol = ""
style = "fg:color_purple"
format = '[ $symbol $version]($style)'

[java]
symbol = ""
style = "fg:color_orange"
format = '[ $symbol $version]($style)'

[kotlin]
symbol = ""
style = "fg:color_purple"
format = '[ $symbol $version]($style)'

[haskell]
symbol = ""
style = "fg:color_purple"
format = '[ $symbol $version]($style)'

[python]
symbol = ""
style = "fg:color_yellow"
format = '[ $symbol $version]($style)'

[vagrant]
symbol = "⍱"
style = "fg:color_blue"
format = '[ $symbol $version]($style)'

[package]
symbol = "󰏗"
style = "fg:color_red"
format = '[ $symbol $version]($style)'

[docker_context]
symbol = ""
style = "fg:color_blue"
format = '[ $symbol $context]($style)'

[conda]
style = "fg:color_green"
format = '[ $symbol $environment]($style)'

[time]
disabled = true
time_format = "%R"
style = "fg:color_bg3"
format = '[  $time]($style)'

[cmd_duration]
min_time = 500
style = "fg:color_yellow"
format = '[ 󰔟 $duration]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'
